[package]
name = "unicode-hieroglyphs-extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
signlist-core = { path = "../signlist-core" }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

